-- Inserts for Examene
INSERT INTO examene (examen, data_examen, total_intrebari) VALUES ('Matematica', '2024-06-01', 6), ('Informatica', '2024-06-02', 6), ('Fizica', '2024-06-03', 6), ('Chimie', '2024-06-04', 6);

-- Inserts for Studenti
INSERT INTO studenti (nume, prenume, email) VALUES('Popescu', 'Ion', 'ion.popescu@example.com'),('Ionescu', 'Maria', 'maria.ionescu@example.com'),('Georgescu', 'Andrei', 'andrei.georgescu@example.com'),('Dumitrescu', 'Ana', 'ana.dumitrescu@example.com'),('Vasilescu', 'Mihai', 'mihai.vasilescu@example.com'),('Petrescu', 'Elena', 'elena.petrescu@example.com'),('Marinescu', 'Cristian', 'cristian.marinescu@example.com'),('Stoica', 'Alexandra', 'alexandra.stoica@example.com'),('Grigorescu', 'Raluca', 'raluca.grigorescu@example.com'),('Ciobanu', 'Victor', 'victor.ciobanu@example.com');

-- Inserts for Inscrieri
Insert into inscrieri (student_id, examen_id) values (1, 2), (1, 4), (2,2), (3,2), (4, 1), (4, 2);

-- Inserts for Intrebari
INSERT INTO intrebari (intrebare, examen_id) VALUES('Care este rezultatul adunării 2+3?', 1), ('Ce este o fracție?', 1), ('Cum se calculează aria unui dreptunghi?', 1), ('Ce reprezintă numărul π?', 1), ('Ce este un număr prim?', 1), ('Rezultatul înmulțirii 6x7?', 1),('Ce este un algoritm?', 2), ('Ce înseamnă OOP?', 2), ('Care este diferența dintre RAM și ROM?', 2), ('Ce este un sistem de operare?', 2), ('Care este scopul unui limbaj de programare?', 2), ('Ce este HTML?', 2),('Care este formula vitezei?', 3), ('Ce este energia potențială?', 3), ('Cum se definește accelerația?', 3), ('Ce este forța de frecare?', 3), ('Ce este viteza luminii?', 3), ('Cum se măsoară tensiunea electrică?', 3),('Care este simbolul chimic pentru apă?', 4), ('Ce reprezintă pH-ul?', 4), ('Care este diferența dintre acid și bază?', 4), ('Ce este o moleculă?', 4), ('Ce înseamnă reacție chimică?', 4), ('Care este simbolul chimic pentru oxigen?', 4);

INSERT INTO raspunsuri (variantaA, variantaB, intrebare_id) VALUES ('5', '4', 1), ('O parte a unui întreg', 'Un număr întreg', 2), ('Lungime x Lățime', 'Lungime + Lățime', 3), ('Număr irațional', 'Număr rațional', 4), ('Număr divizibil doar cu 1 și el însuși', 'Număr par', 5), ('42', '36', 6),('O secvență de pași', 'Un program', 7), ('Programare Orientată pe Obiecte', 'Protocol de rețea', 8), ('RAM este volativ, ROM este permanent', 'ROM este volativ, RAM este permanent', 9), ('Software de bază', 'Limbaj de programare', 10), ('Creare aplicații', 'Editare imagini', 11), ('HyperText Markup Language', 'High Transfer Messaging Language', 12),('v = d/t', 'v = t/d', 13), ('Energia unui obiect datorită poziției', 'Energia unui obiect în mișcare', 14), ('Schimbarea vitezei în timp', 'Forță aplicată', 15), ('Rezistența mișcării', 'Accelerare constantă', 16), ('300,000 km/s', '150,000 km/s', 17), ('Volt', 'Amper', 18),('H2O', 'O2H', 19), ('Măsura acidității', 'Măsura concentrației', 20), ('Acid cedează protoni, baza îi acceptă', 'Baza cedează protoni, acidul îi acceptă', 21), ('Două sau mai multe atome legate', 'Un singur atom', 22), ('Transformare chimică', 'Dizolvare', 23), ('O2', 'O', 24);